<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { ConfettiCannon } from 'svelte-canvas-confetti';
  import Editor from '../component/editor.svelte';
  import Notification from '../component/notification.svelte';
  import { streak, last } from '$lib/store';
  import Timer from '../component/timer.svelte';
  import Streak from '../component/streak.svelte';
  import Tree from '../component/tree.svelte';

  let code: any;
  let challengeData: any;
  let title: string = '';
  let description: string = '';
  let confettiCannon = false;
  let status = 0;

  let notificationShow: boolean;
  let notificationContent: string;

  const runFunction = () => {
    try {
      let functionParameters = code.split('(')[1].split(')')[0];
      if (functionParameters.includes(',')) {
        functionParameters = functionParameters.split(',');
      }
      let functionBody = code.substring(
        code.indexOf('{') + 1,
        code.lastIndexOf('}')
      );
      let fn;
      switch (challengeData.test.length) {
        case 2:
          fn = new Function(
            functionParameters[0],
            functionParameters[1],
            functionBody
          );
          return fn(challengeData.test[0], challengeData.test[1]);
        case 1:
          fn = new Function(functionParameters, functionBody);
          return fn(challengeData.test[0]);
        default:
          fn = new Function(functionBody);
          return fn();
      }
    } catch (e) {
      status = -1;
      setTimeout(() => (status = 0), 1500);
    }
  };

  const submitClicked = async () => {
    if (status == -1 || status == 1) return;
    const result = runFunction();

    if (
      result == challengeData.expected ||
      JSON.stringify(result) == JSON.stringify(challengeData.expected)
    ) {
      status = 1;
      streak.set($streak + 1);
      last.set(new Date().getTime());
      confettiCannon = false;
      await tick();
      confettiCannon = true;
    } else {
      status = -1;
      notificationShow = true;
      notificationContent = runFunction();
      setTimeout(() => (status = 0), 1500);
    }
  };

  const notificationCallback = () => {
    notificationShow = false;
  };

  const checkLast = () => {
    var today = new Date().setHours(0, 0, 0, 0);
    var lastDay = new Date($last).setHours(0, 0, 0, 0);
    if (today === lastDay) {
      status = 1;
    }
  };

  onMount(async () => {
    const day = new Date().getDate();
    const resp = await fetch('/challenges.json');
    const respJson = await resp.json();
    challengeData = respJson.data[day];
    title = challengeData.title;
    description = challengeData.description;
    checkLast();
  });
</script>

<h2
  class="hidden lg:block text-7xl text-center text-white-300 font-bold mb-6 lg:mb-8 font-share"
>
  C0DLE - JS Edition
</h2>

<h2
  class="lg:hidden text-5xl text-center text-white-300 font-bold mt-3 lg:mt-0 lg:mb-8 font-share"
>
  C0DLE
</h2>

<h2
  class="lg:hidden text-2xl text-center text-white-300 font-bold lg:mt-0 lg:mb-12 font-share"
>
  JS Edition
</h2>

<div class="flex flex-col lg:flex-row items-center">
  <Streak />
  <Timer />
</div>

<div class="group relative block w-full">
  <div class="relative flex justify-center h-full rounded-2xl bg-gray-100">
    <div class="text-white-100 p-4 sm:p-6 lg:p-8">
      <h2 class="text-xl text-center font-share font-bold sm:text-2xl">
        {title}
      </h2>

      <p
        class="mt-4 text-justify font-semibold font-share text-sm sm:text-base"
      >
        {description}
      </p>
    </div>
  </div>
</div>

<div class="group relative block w-full">
  {#if challengeData}
    <Editor
      bind:editorContent={code}
      variables={['a', 'b']
        .slice(0, challengeData.test.length)
        .toString()
        .replace(',', ', ')}
    />
  {/if}
</div>

<Tree></Tree>

<div class="relative flex flex-col justify-between w-full mt-6">
  <button
    class="rounded-full w-full py-3 px-8 flex-grow-1 bg-green-200 uppercase font-share text-white-300 font-semibold hover:line-through disabled:line-through disabled:bg-green-100"
    class:wrong={status == -1}
    disabled={status == 1}
    on:click={submitClicked}
  >
    Submit {#if status == 0}🤔{:else if status == -1}😢{:else}😀{/if}
  </button>
  {#if notificationShow}
    <Notification
      bind:content={notificationContent}
      callback={notificationCallback}
    />
  {/if}
</div>

{#if confettiCannon}
  <ConfettiCannon
    origin={[window.innerWidth * 0.7, window.innerHeight * 0.8]}
    angle={-90}
    spread={120}
    force={25}
  />
{/if}

<style>
  .wrong {
    -webkit-animation: shake-bottom 0.6s cubic-bezier(0.455, 0.03, 0.515, 0.955)
      both;
    animation: shake-bottom 0.6s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-11-11 17:36:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation shake-bottom
 * ----------------------------------------
 */
  @-webkit-keyframes shake-bottom {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 100%;
      transform-origin: 50% 100%;
    }
    10% {
      -webkit-transform: rotate(1deg);
      transform: rotate(1deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    80% {
      -webkit-transform: rotate(-1deg);
      transform: rotate(-1deg);
    }
    90% {
      -webkit-transform: rotate(1deg);
      transform: rotate(1deg);
    }
  }
  @keyframes shake-bottom {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 100%;
      transform-origin: 50% 100%;
    }
    10% {
      -webkit-transform: rotate(1deg);
      transform: rotate(1deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    80% {
      -webkit-transform: rotate(-1deg);
      transform: rotate(-1deg);
    }
    90% {
      -webkit-transform: rotate(1deg);
      transform: rotate(1deg);
    }
  }

  @keyframes animate {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  @keyframes animate2 {
    0% {
      transform: rotate(360deg);
    }
    100% {
      transform: rotate(0deg);
    }
  }
</style>
